version: '3'

services:
  fountain:
    volumes:
    # for development
    - ./src/fountain:/src/fountain
    working_dir: /src/fountain
    env_file:
    - ./src/.env.development
  fountainpy:
    volumes:
    # for development
    - ./src/fountainpy:/src/fountainpy
    working_dir: /src/fountainpy
    env_file:
    - ./src/.env.development
