version: '3'

services:
  # bot:
  #   volumes:
  #   # for development
  #   - ./src/bot:/src/bot
  #   working_dir: /src/bot
  #   env_file:
  #   - ./.env.development
  bot-nodejs:
    volumes:
    # for development
    - ./src/bot-nodejs:/src/bot-nodejs
    working_dir: /src/bot-nodejs
    env_file:
    - ./.env.development
